# Compiler and flags
CC = gcc
CFLAGS = -g -ansi -pedantic -Wall

# Source files
FILES = main.c coursesArray.c displayR.c dropTable.c findIndex.c mallocR.c registrationTable.c studentsArray.c
# Object files (generated by replacing .c with .o)
OBJS = $(FILES:.c=.o)

# Output executable name
OUT_EXE = main

# Default target: build the executable
all: $(OUT_EXE)

# Rule to build the executable from object files
$(OUT_EXE): $(OBJS)
	$(CC) $(CFLAGS) -o $(OUT_EXE) $(OBJS)

# Rule to build object files from source files
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Clean up build artifacts
clean:
	rm -f $(OBJS) $(OUT_EXE) core *.exe *~

# Rebuild target
rebuild: clean all
